'use client';

import { useState, useRef } from 'react';
import { motion, AnimatePresence, useInView } from 'framer-motion';
import { Plus } from 'lucide-react';
import { cn } from '@/lib/utils';

/*
  These answers describe what the system actually does today.

  They previously claimed 50+ supported file types, fully air-gapped on-premise
  deployment, a quarterly-updated DGMS regulatory knowledge base, 48-72 hour
  rollouts against SharePoint/S3, native SAP and Oracle ERP integrations, and
  SLA-backed enterprise tiers. None of that exists. The accuracy answer below
  had already been rewritten honestly; the rest had not.

  Rule for this file: an answer must be checkable against the repo. If a
  capability is planned but unbuilt, say so — integration-grid.tsx is badged
  "Roadmap — not yet built" and that is the pattern to follow.
*/
const faqs = [
  {
    q: 'What types of documents does MiningNiti support?',
    a: 'PDF, Word (.docx) and plain text, up to 50MB per file. Scanned PDFs are handled: text is extracted with pdfplumber, and pages that come back empty fall back to OCR via Tesseract. Extraction is layout-aware — tables are rendered as Markdown rather than flattened into a text stream, because a regulation table flattened into prose is not merely lossy, it is confidently wrong once embedded and cited. Spreadsheets, images and email archives are not supported yet.',
  },
  {
    q: 'Where does my data go?',
    a: "Be aware of what this is: a hosted demo. Documents are stored in Supabase, the API runs on Hugging Face Spaces, and answers are generated by third-party model providers (Groq, Cerebras, Mistral) with embeddings from Google. Your documents are sent to those providers as retrieved context. The whole stack is open source and ships with Docker Compose, so you can run the API, Postgres and Redis on your own infrastructure — but the model calls still leave your network. There is no air-gapped build today.",
  },
  {
    q: 'How does MiningNiti handle DGMS and Indian mining regulations?',
    a: 'There is no bundled regulatory corpus — you supply the regulations. Upload a regulation document, pick the operational documents to audit against it, and the compliance auditor walks it clause by clause: each clause is used to retrieve evidence from your operational documents, then assessed as compliant, gap, or missing, with a confidence score and the supporting passages and page numbers attached. That means it works on DGMS, the Mines Act, MSHA parts, or an internal standard equally well — but nothing is pre-loaded for you.',
  },
  {
    q: 'How long does it take to get started?',
    a: "Minutes, because there is nothing to deploy — sign in and upload a document. Processing runs in the background: extraction, chunking, embedding, then four AI agents that classify the document, score its safety content, extract entities and summarise it. You can watch the status change on the documents page and query the document as soon as it completes. There are no connectors for SharePoint, shared drives or S3; upload is direct.",
  },
  {
    q: 'Can MiningNiti integrate with our existing ERP or operations software?',
    a: 'Through the REST API, yes — the backend exposes an OpenAPI schema at /docs covering documents, chat, search, compliance audits and analytics, authenticated with a bearer token. What does not exist yet are packaged connectors: there is no native SAP, Oracle ERP or Microsoft 365 integration and no webhook system. Those are on the roadmap, not in the product.',
  },
  {
    q: 'How accurate is the AI extraction on old or low-quality scans?',
    a: 'Text is extracted with pdfplumber, and pages that come back empty — typically scans — fall back to OCR. We do not publish an extraction accuracy figure, because we have not measured one on a representative corpus and a number we cannot reproduce would be worse than none. What is measured is retrieval: against a labelled golden set, the pipeline scores 1.00 Hit Rate@5 and 0.97 nDCG@5, and that check runs as a blocking gate in CI. Every answer also cites the document and page it came from, so any claim can be checked against the source.',
  },
  {
    q: 'Is this a product I can buy?',
    a: 'Not yet — MiningNiti is an open-source platform and a working public demo, not a commercial offering. There are no pricing tiers, no SLA and no support contract. The hosted demo runs entirely on free infrastructure, so the API sleeps when idle and the first request after a quiet period can take up to a minute to wake. The source is MIT-licensed and self-hostable if you want to run it against your own documents.',
  },
];

export function FaqSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: '-80px' });

  return (
    <section ref={ref} className="py-24 sm:py-32 bg-[#05030A] border-t border-white/5 relative overflow-hidden" id="faq">

      <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-[radial-gradient(ellipse_at_bottom,rgba(148,122,252,0.06),transparent_70%)] pointer-events-none" />

      <div className="mx-auto max-w-[1200px] px-6 relative z-10">
        
        <div className="grid lg:grid-cols-[1fr_1.8fr] gap-16 lg:gap-24 items-start">
          
          {/* Left — Sticky heading */}
          <div className="lg:sticky lg:top-32">
            <motion.p
              initial={{ opacity: 0, y: 16 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5 }}
              className="text-[11px] font-mono tracking-[0.2em] uppercase text-purple-400 mb-4"
            >
              FAQ
            </motion.p>
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="text-[clamp(2rem,4vw,3rem)] font-bold tracking-tight text-white leading-[1.1] mb-6"
            >
              Questions & Answers
            </motion.h2>
            <motion.p
              initial={{ opacity: 0, y: 16 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="text-white/50 text-[16px] leading-relaxed mb-8"
            >
              Everything you need to know about deploying MiningNiti in your operation.
            </motion.p>
            <motion.a
              initial={{ opacity: 0, y: 16 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: 0.3 }}
              href="mailto:hello@miningniti.com"
              className="inline-flex items-center gap-2 text-sm font-medium text-purple-400 hover:text-white transition-colors"
            >
              Still have questions? Contact us
              <svg width="11" height="11" viewBox="0 0 11 11" fill="none">
                <path d="M1 5.5H10M10 5.5L5.5 1M10 5.5L5.5 10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </motion.a>
          </div>

          {/* Right — Accordion */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={isInView ? { opacity: 1 } : {}}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="divide-y divide-white/[0.07]"
          >
            {faqs.map((faq, i) => {
              const isOpen = openIndex === i;
              return (
                <div key={i} className="py-5">
                  <button
                    onClick={() => setOpenIndex(isOpen ? null : i)}
                    className="w-full flex items-start gap-4 text-left group"
                    suppressHydrationWarning
                  >
                    <motion.span
                      animate={{ rotate: isOpen ? 45 : 0 }}
                      transition={{ duration: 0.25, ease: [0.16, 1, 0.3, 1] }}
                      className={cn(
                        'size-6 rounded-full border flex items-center justify-center shrink-0 mt-0.5 transition-colors duration-200',
                        isOpen
                          ? 'border-[#947AFC] bg-purple-400/10'
                          : 'border-white/20 group-hover:border-white/40'
                      )}
                    >
                      <Plus className={cn('size-3 transition-colors duration-200', isOpen ? 'text-purple-400' : 'text-white/50')} />
                    </motion.span>
                    <span className={cn(
                      'text-[15px] font-semibold leading-snug transition-colors duration-200',
                      isOpen ? 'text-white' : 'text-white/70 group-hover:text-white'
                    )}>
                      {faq.q}
                    </span>
                  </button>

                  <AnimatePresence initial={false}>
                    {isOpen && (
                      <motion.div
                        key="content"
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.35, ease: [0.16, 1, 0.3, 1] }}
                        className="overflow-hidden"
                      >
                        <p className="pt-4 pl-10 text-[15px] text-white/55 leading-[1.75]">
                          {faq.a}
                        </p>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              );
            })}
          </motion.div>

        </div>
      </div>
    </section>
  );
}
